server:
  port: 8011
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtoauth2
    username: root
    password: firstnext1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
